# TensorFlow Fundamentals

In [ ]:
## Importing Tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


## Creating Tensor in ML

### Creating Tensor with tf.constant()

In [ ]:
## Creating tensor(Scaler) with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
## Checking the dimension of a tensor(ndim --> Number of Dimensions)
scaler.ndim

0

In [ ]:
# Create a tensor(vector) using tf.constant()
vector = tf.constant([10,15])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 15], dtype=int32)>

In [ ]:
## Checking the dimension of our vector(ndim --> Number of Dimensions)
vector.ndim

1

In [ ]:
## Create a tensor(Matrix) (has more than 1-Dimension)
matrix = tf.constant([[10,2,3],[6,8,12],[1,54,2]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  2,  3],
       [ 6,  8, 12],
       [ 1, 54,  2]], dtype=int32)>

In [ ]:
## Checking the dimension of our matrix(ndim --> Number of Dimensions)
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[12.,10,5],[5,6.,75]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[12., 10.,  5.],
       [ 5.,  6., 75.]], dtype=float16)>

In [ ]:
tensor = tf.constant([[[12,5],[6,8],[8,78]],
                      [[54.25,540],[5,5.6],[6.9,9]]], dtype = tf.float16)
tensor

<tf.Tensor: shape=(2, 3, 2), dtype=float16, numpy=
array([[[ 12.  ,   5.  ],
        [  6.  ,   8.  ],
        [  8.  ,  78.  ]],

       [[ 54.25, 540.  ],
        [  5.  ,   5.6 ],
        [  6.9 ,   9.  ]]], dtype=float16)>

In [ ]:
tensor.ndim

3

### Creating tensor with tf.Variable()

In [ ]:
mutable_tensor = tf.Variable([7,10])
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

> Cannot do mutable_tensor[0] = (11) Not allowed
`mutable_tensor[0] = 11`

In [ ]:
mutable_tensor[0].assign(11)
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11, 10], dtype=int32)>

## Random Tensor 

### Create a Random Tensor

In [ ]:
random_1 = tf.random.Generator.from_seed(24)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(24)
random_2 = random_2.normal(shape = (3,2))

# Are They Equal

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 ],
        [-0.14371012, -0.34646833]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 ],
        [-0.14371012, -0.34646833]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the Elements Order in the Tensor

In [ ]:
not_shuffled = tf.constant([[5,11,1],[3,14,5],[6,7,0]])
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11,  1],
       [ 3, 14,  5],
       [ 6,  7,  0]], dtype=int32)>

In [ ]:
not_shuffled.ndim

2

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 6,  7,  0],
       [ 3, 14,  5],
       [ 5, 11,  1]], dtype=int32)>

In [ ]:
tf.random.set_seed(45)
tf.random.shuffle(not_shuffled , seed = 45)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11,  1],
       [ 3, 14,  5],
       [ 6,  7,  0]], dtype=int32)>

### Other ways to make Tensors

In [ ]:
tf.ones([3,4], tf.int16)


<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [ ]:
tf.zeros([3,4], tf.int16)

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

### Turning NumPy Arrays into Tensors

In [ ]:
import numpy as np
np_array = np.arange(1, 25, dtype = np.int16)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [ ]:
tensor_np = tf.convert_to_tensor(np_array, dtype= tf.int32)
tensor_np

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(np_array, shape=(3,2,4))
B = tf.constant(np_array, shape=(6,4))
C = tf.constant(np_array)

A , B , C 

(<tf.Tensor: shape=(3, 2, 4), dtype=int16, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int16)>,
 <tf.Tensor: shape=(6, 4), dtype=int16, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=int16)>,
 <tf.Tensor: shape=(24,), dtype=int16, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int16)>)

In [ ]:
A.ndim , B.ndim , C.ndim

(3, 2, 1)

### Getting Information From Tensors

In [ ]:
tensor

<tf.Tensor: shape=(2, 3, 2), dtype=float16, numpy=
array([[[ 12.  ,   5.  ],
        [  6.  ,   8.  ],
        [  8.  ,  78.  ]],

       [[ 54.25, 540.  ],
        [  5.  ,   5.6 ],
        [  6.9 ,   9.  ]]], dtype=float16)>

In [ ]:
tensor.shape

TensorShape([2, 3, 2])

In [ ]:
tensor.ndim

3

In [ ]:
tensor[0], tensor[:,1], tensor[1:,:1]

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[12.,  5.],
        [ 6.,  8.],
        [ 8., 78.]], dtype=float16)>,
 <tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[6. , 8. ],
        [5. , 5.6]], dtype=float16)>,
 <tf.Tensor: shape=(1, 1, 2), dtype=float16, numpy=array([[[ 54.25, 540.  ]]], dtype=float16)>)

In [ ]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5), dtype= tf.int16)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int16, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int16)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int16, numpy=
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int16)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
rank_4_tensor.dtype, rank_4_tensor.shape[0], rank_4_tensor.shape[-1]

(tf.int16, 2, 5)

In [ ]:
tf.size(rank_4_tensor), tf.size(rank_4_tensor).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=120>, 120)

### Indexing Tensors

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int16, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int16)>

In [ ]:
rank_4_tensor[:1,:1,:4,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int16, numpy=
array([[[[0],
         [0],
         [0],
         [0]]]], dtype=int16)>

In [ ]:
rank_2_tensor = tf.ones(shape= (3,4), dtype=tf.int16)
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([3, 4]))

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [ ]:
rank_2_tensor[:,1:-1]

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)>